# Generated by Django 5.0 on 2024-05-30 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('man', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='man',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='man.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='man',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='man.tagpost', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='man',
            name='wife',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woman', to='man.wife', verbose_name='Жена'),
        ),
        migrations.AddIndex(
            model_name='man',
            index=models.Index(fields=['-time_create'], name='man_man_time_cr_3b5135_idx'),
        ),
    ]
